repos:
  # Use local to make sure the dependencies are taken from pre-commit's own environment and
  # therefore from our nix derivation.
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: Ensure each file ends with a single newline
        entry: end-of-file-fixer
        language: system
        types: [text]
      - id: trailing-whitespace-fixer
        name: Trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
      - id: typos
        name: Typos
        entry: typos --write-changes
        language: system
        types: [text]
        exclude_types: [diff, json]
        exclude: ^(libs/opsqueue_python/examples/capitalize_text/lipsum\.txt|libs/opsqueue_python/examples/capitalize_text/more_lipsum\.txt)$
      - id: ruff-check
        name: Ruff linting
        entry: ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: Ruff formatting
        entry: ruff format
        language: system
        types: [python]
        require_serial: true
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: nixfmt
        name: nixfmt
        entry: nixfmt --strict
        language: system
        types: [nix]
        exclude: extra
      - id: sqlx-test-needs-migrator
        name: Require `#[sqlx::test(migrator = "crate::MIGRATOR")]` for test-build speed
        entry: '#\[sqlx::test\]'
        language: pygrep
        types: [rust]
