allowed-duplicate-crates = [
    "block-buffer",
    "cpufeatures",
    "crypto-common",
    "digest",
    "getrandom",
    "hashbrown",
    "r-efi",
    "rand",
    "rand_core",
    "sha1",
    "sha2",
    "syn",
    "thiserror",
    "tokio-tungstenite",
    "tower-http",
    "tungstenite",
    "windows-sys",
]
