allowed-duplicate-crates = [
    "block-buffer",
    "cpufeatures",
    "crypto-common",
    "digest",
    "foldhash",
    "getrandom",
    "hashbrown",
    "r-efi",
    "rand",
    "rand_chacha",
    "rand_core",
    "redox_syscall",
    "sha1",
    "sha2",
    "syn",
    "thiserror",
    "tower-http",
    "windows",
    "windows-sys",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
