name: Checkout & Setup
description: Checks out the git repo and sets up Nix, Direnv and Rust, with appropriate caching
runs:
  using: "composite"
  steps:
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'nix/sources.json') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
    - uses: HatsuneMiku3939/direnv-action@v1
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: "true"
